### PR TITLE
I38 redux

### LINKED ISSUE #38: use redux for state
The app currently needs to store:
- A classifier in the process of being built
- A set of already built classifiers
- An annotation in the process of being built
- A set of annotations already built
- A set of annotation+classifier which contain the results of a classifier used on a given annotated area

Where should this be stored?
1. In Menu, and passed down to other react classes via props?
2. Using something like redux?

I'm leaning towards 2 so I can learn how redux works....

### PR DESCRIPTION
**Pull request by martinjrobins**
This ended up being a large PR! sorry

- created redux store, containing 
       (a) created annotations, 
       (b) current annotation
       (c) created classifiers
       (d) current classifier
       (e) results of prediction
- created Annotation container (`src/containers/Annotation.jsx`) linked to store and Annotation component (`src/components/Classifier.jsx`)
- created Classifier container (`src/containers/Annotation.jsx`) linked to store and Classifier component (`src/components/Classifier.jsx`)
- created Menu container
- created Predict container. Modified behaviour of Predict component so that the selected classifier is applied to *all* created annotations

Fixes #38 
also part of https://github.com/OxfordRSE/Electron-Sight/issues/32#issuecomment-565381383

### CODE REVIEW

**Review by iamleeg — CHANGES_REQUESTED** [review]
This is great for separating concerns and managing the app's growing complexity! I'd like to see the `ApplicationState` moved to redux state and handled by the reducer, because then we've only got a single system for state management.

I'm happy to try to do that myself and add it to this PR, if that's easier.

**Comment by martinjrobins** [comment]
Yes, agreed, be good to have `ApplicationState` in the redux state as well, please do that and add to the PR, thanks @iamleeg!

**Review by iamleeg — APPROVED** [review]
There's one more bit of complexity that was uncovered by making the ApplicationState change, and I've swept it under the carpet for now. But I'll mention it, so we know about it and can decide what to do.

I had to introduce an asynchronous action for clicking in Annotate mode, because you're not allowed to call actions from the reducer (as you're in the middle of updating the state already). The underlying reason is that the `ApplicationState` has the click handler, which doesn't really fit the redux pattern. We need to think about how to address that, but my kludge fix at least works.

**Comment by iamleeg** [comment]
I've undone the async stuff, and stopped using a reducer for the click handling.

**Review by martinjrobins — COMMENTED** [review]
great, thanks @iamleeg. I'll merge that in

**Pull request merged**
